## Site Data 
site_name: Cockatrice - Magic The Gathering Wiki
site_author: Adaendra

## Navigation
nav: 
  - Accueil : index.md

## Theme
theme:
  name: null
  custom_dir: 'custom_theme/magic_wiki/'
