## Site Data 
site_name: Cockatrice - Magic The Gathering
site_author: Adaendra

## Navigation
nav: 
  - Accueil : index.md
  - Modes et formats: modes_and_formats.md

## Theme
theme:
  name: null
  custom_dir: 'custom_theme/magic_wiki/'
  navigation_depth: 4
