## Site Data 
site_name: Cockatrice - Magic The Gathering
site_author: Adaendra

## Navigation
nav: 
  - Accueil : index.md
  - Modes et formats:
    - Modes: modes.md
    - Formats: formats.md
  - Decks :
    - Classique:
      - Gobelins : decks/classique/gobelins.md

## Theme
theme:
  name: null
  custom_dir: 'custom_theme/magic_wiki/'
  navigation_depth: 2
